# Generated by Django 3.2 on 2024-06-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_shoppingcart_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'объект «Тег»', 'verbose_name_plural': '«Теги»'},
        ),
    ]
