# Generated by Django 3.2 on 2024-07-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgramuser',
            name='second_name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
