# Generated by Django 3.2 on 2024-06-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240611_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='foodgram/images/'),
        ),
    ]
