# Generated by Django 3.2 on 2024-07-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_foodgramuser_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='second_name',
            field=models.CharField(max_length=254, null=True, verbose_name='Отчество'),
        ),
    ]
